### ISSUE TITLE
Demeter listing request

### ISSUE THREAD

**Issue by MasterRadule** [yield-bay/listing-requests#1]
*[Mandatory Information]*
## Name of protocol : Demeter
Number of farms available on protocol: 13

- On Demeter Farming platform, users are able to farm with same LP in multiple pools (for example with XOR/ETH, they can farm in pool with DEO rewards, in pool with CERES rewards etc...).

## Top farms on the platform:
1. XOR/VAL ([link1](https://farming.deotoken.io/))
2. XOR/ETH ([link2](https://farming.deotoken.io/))
3. XOR/XST ([link3](https://farming.deotoken.io/))

## Data fetching
SORA network on which Demeter Farming platform is running is made in Substrate and is heading to be Polkadot parachain. So everything you need to call on-chain, you can through Polkadot portal: https://polkadot.js.org/apps/?rpc=wss://ws.mof.sora.org#/chainstate. Here you can select `demeterFarmingPlatform` pallet and query pools. As a parameters you need to provide `asset ids` of pool asset and reward asset (for example for XOR/ETH pool with DEO rewards provide ETH and DEO asset ids respectively). I am providing example in attachments.

![image](https://user-images.githubusercontent.com/16464173/214061810-280c005b-6598-41d8-a320-59d3d213f744.png)

In the attachment, I provided ETH and DEO asset ids and got info about the pool (deposit fee, is it farming or staking pool, total rewards...). Also I got baseAsset, that is the XOR's asset id because farming pools is XOR/ETH with DEO rewards.
However, it is a bit tricky (a lot of calculations) to get the APR data, TVL etc... But we can provide API with that data, we already have API for getting all pools and TVL (provided in API/SDK section below).

## Contact information
Telegram (the best way to contact) - https://t.me/DanijelCeres
Mail - danijel.radulovic@cerestoken.io

---

*[Optional Information - helps us easily integrate your protocol]*

### API/SDK for fetching real-time farms/rewards/token data
Get all farming pools - https://farming-api.cerestoken.io/get-farms
Get TVL - https://farming-api.cerestoken.io/get-supply-data

### Farm type: 
1. Pallet: pallet name(s) and methods to fetch farm data.
Pallet - `demeterFarmingPlatform`
Methods - `pools, tokenInfos, userInfos`

**Comment by nightwing-yb** [comment]
Integrated! 

Can be viewed [here](https://list.yieldbay.io?q=demeter).
