### ISSUE TITLE
DAM Finance listing request

### ISSUE THREAD

**Issue by noah-foltz** [yield-bay/listing-requests#2]
## Name of protocol : [DAM Finance](https://dam.finance/)
Number of farms available on protocol: **1**

## Top farms on the platform:
1. [d2o/xcUSDT -> GLMR Rewards](https://curve.fi/#/moonbeam/pools/factory-v2-18/)

## Data fetching

Current API info on the Moonbeam curve deployment seems limited to this page: 
https://api.curve.fi/api/getPools/moonbeam/factory

The id of DAM's pool is "factory-v2-18" in the poolData list. 
Address:  [0xFF6DD348e6eecEa2d81D4194b60c5157CD9e64f4](0xFF6DD348e6eecEa2d81D4194b60c5157CD9e64f4)
Name: Curve.fi Factory Plain Pool: d2o/xcUSDT

Our current historical APR is 186.948% since inception from WGLMR rewards, but with higher TVL we are targeting 20% APY. Current daily APY is 0.047%. Fees are 0.04%, with liquidity providers getting half of that fee per transaction. 
Our current TVL is $62,464.75

[d2o Address on Moonbeam](https://moonscan.io/token/0xc806B0600cbAfA0B197562a9F7e3B9856866E9bF)
[d2o Address on Ethereum](https://etherscan.io/address/0x2FdA8c6783Aa36BeD645baD28a4cDC8769dCD252)

## Contact information

DAM Discord: https://discord.com/invite/gG9b7YrPH6
DAM Twitter: https://twitter.com/DAM_Finance
My Twitter: https://twitter.com/noah_foltz
My Telegram: @noahfoltz

**Comment by 0xSonOfNeptune** [comment]
Closed via https://github.com/yield-bay/bay-watcher/commit/59de5df5ae12e5baa83ce8bb9a80e43e77310efc
